export let PRODUCT_GET_PENDING = "PRODUCT_GET_PENDING"
export let PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS"
export let PRODUCT_GET_ERROR = "PRODUCT_GET_ERROR"

export let PRODUCT_POST_SUCCESS = "PRODUCT_POST_SUCCESS"
export let PRODUCT_POST_PENDING = "PRODUCT_POST_PENDING"
export let PRODUCT_POST_ERROR = "PRODUCT_POST_ERROR"

export let PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export let PRODUCT_DELETE_PENDING = "PRODUCT_DELETE_PENDING"
export let PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR"

export let PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS"
export let PRODUCT_UPDATE_PENDING = "PRODUCT_UPDATE_PENDING"
export let PRODUCT_UPDATE_ERROR = "PRODUCT_UPDATE_ERROR"